/**
 * Role Types
 */
const ROLES = {
  ADMIN: 'ADMIN',
  CONTENT_MANAGER: 'CONTENT_MANAGER',
  EDITOR: 'EDITOR',
  CONTENT_WRITER: 'CONTENT_WRITER',
  VIEWER: 'VIEWER'
};

/**
 * All Available Permissions
 */
const PERMISSIONS = {
  // Full Access (Admin Only)
  ALL: 'ALL',

  // Admin Management Permissions (Super Admin Only)
  CREATE_ADMIN: 'CREATE_ADMIN',
  DELETE_ADMIN: 'DELETE_ADMIN',
  MANAGE_ADMINS: 'MANAGE_ADMINS',

  // Article Permissions
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  EDIT_OWN_ARTICLE: 'EDIT_OWN_ARTICLE',
  EDIT_ANY_ARTICLE: 'EDIT_ANY_ARTICLE',
  DELETE_OWN_ARTICLE: 'DELETE_OWN_ARTICLE',
  DELETE_ANY_ARTICLE: 'DELETE_ANY_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  VIEW_ARTICLE: 'VIEW_ARTICLE',
  PUBLISH_ARTICLE: 'PUBLISH_ARTICLE',
  APPROVE_ARTICLE: 'APPROVE_ARTICLE',
  REJECT_ARTICLE: 'REJECT_ARTICLE',

  // Category Permissions
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  VIEW_CATEGORY: 'VIEW_CATEGORY',

  // Hero Content Permissions
  CREATE_HERO_CONTENT: 'CREATE_HERO_CONTENT',
  EDIT_HERO_CONTENT: 'EDIT_HERO_CONTENT',
  DELETE_HERO_CONTENT: 'DELETE_HERO_CONTENT',
  VIEW_HERO_CONTENT: 'VIEW_HERO_CONTENT',
  MANAGE_HERO_CONTENT: 'MANAGE_HERO_CONTENT',

  // Carousel Permissions
  CREATE_CAROUSEL: 'CREATE_CAROUSEL',
  EDIT_CAROUSEL: 'EDIT_CAROUSEL',
  DELETE_CAROUSEL: 'DELETE_CAROUSEL',
  VIEW_CAROUSEL: 'VIEW_CAROUSEL',

  // Course Permissions
  CREATE_COURSE: 'CREATE_COURSE',
  EDIT_COURSE: 'EDIT_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  VIEW_COURSE: 'VIEW_COURSE',

  // University Permissions
  CREATE_UNIVERSITY: 'CREATE_UNIVERSITY',
  EDIT_UNIVERSITY: 'EDIT_UNIVERSITY',
  DELETE_UNIVERSITY: 'DELETE_UNIVERSITY',
  VIEW_UNIVERSITY: 'VIEW_UNIVERSITY',

  // Document Permissions
  CREATE_DOCUMENT: 'CREATE_DOCUMENT',
  EDIT_DOCUMENT: 'EDIT_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  VIEW_DOCUMENT: 'VIEW_DOCUMENT',
  MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',

  // User Management Permissions
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',
  VIEW_USER: 'VIEW_USER',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',

  // Contact Permissions
  VIEW_CONTACT: 'VIEW_CONTACT',
  MANAGE_CONTACT: 'MANAGE_CONTACT',

  // Analytics Permissions
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_REPORTS: 'VIEW_REPORTS',

  // Settings Permissions
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  EDIT_SETTINGS: 'EDIT_SETTINGS',
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',

  // Admin Portal Access
  ACCESS_ADMIN_PORTAL: 'ACCESS_ADMIN_PORTAL'
};

/**
 * Role-Permission Mapping
 */
const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    // Full access - all permissions including admin management
    PERMISSIONS.ALL,
    PERMISSIONS.CREATE_ADMIN,
    PERMISSIONS.DELETE_ADMIN,
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_PERMISSIONS,
    PERMISSIONS.CREATE_ARTICLE,
    PERMISSIONS.EDIT_OWN_ARTICLE,
    PERMISSIONS.EDIT_ANY_ARTICLE,
    PERMISSIONS.DELETE_OWN_ARTICLE,
    PERMISSIONS.DELETE_ANY_ARTICLE,
    PERMISSIONS.DELETE_ARTICLE,
    PERMISSIONS.VIEW_ARTICLE,
    PERMISSIONS.PUBLISH_ARTICLE,
    PERMISSIONS.APPROVE_ARTICLE,
    PERMISSIONS.REJECT_ARTICLE,
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.EDIT_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,
    PERMISSIONS.VIEW_CATEGORY,
    PERMISSIONS.CREATE_HERO_CONTENT,
    PERMISSIONS.EDIT_HERO_CONTENT,
    PERMISSIONS.DELETE_HERO_CONTENT,
    PERMISSIONS.VIEW_HERO_CONTENT,
    PERMISSIONS.MANAGE_HERO_CONTENT,
    PERMISSIONS.CREATE_CAROUSEL,
    PERMISSIONS.EDIT_CAROUSEL,
    PERMISSIONS.DELETE_CAROUSEL,
    PERMISSIONS.VIEW_CAROUSEL,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.EDIT_COURSE,
    PERMISSIONS.DELETE_COURSE,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.CREATE_UNIVERSITY,
    PERMISSIONS.EDIT_UNIVERSITY,
    PERMISSIONS.DELETE_UNIVERSITY,
    PERMISSIONS.VIEW_UNIVERSITY,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.EDIT_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.MANAGE_DOCUMENTS,
    PERMISSIONS.VIEW_CONTACT,
    PERMISSIONS.MANAGE_CONTACT,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.ACCESS_ADMIN_PORTAL
  ],

  [ROLES.CONTENT_MANAGER]: [
    // All content access except user/admin management
    PERMISSIONS.CREATE_ARTICLE,
    PERMISSIONS.EDIT_OWN_ARTICLE,
    PERMISSIONS.EDIT_ANY_ARTICLE,
    PERMISSIONS.DELETE_OWN_ARTICLE,
    PERMISSIONS.DELETE_ANY_ARTICLE,
    PERMISSIONS.DELETE_ARTICLE,
    PERMISSIONS.VIEW_ARTICLE,
    PERMISSIONS.PUBLISH_ARTICLE,
    PERMISSIONS.APPROVE_ARTICLE,
    PERMISSIONS.REJECT_ARTICLE,
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.EDIT_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,
    PERMISSIONS.VIEW_CATEGORY,
    PERMISSIONS.CREATE_HERO_CONTENT,
    PERMISSIONS.EDIT_HERO_CONTENT,
    PERMISSIONS.DELETE_HERO_CONTENT,
    PERMISSIONS.VIEW_HERO_CONTENT,
    PERMISSIONS.MANAGE_HERO_CONTENT,
    PERMISSIONS.CREATE_CAROUSEL,
    PERMISSIONS.EDIT_CAROUSEL,
    PERMISSIONS.DELETE_CAROUSEL,
    PERMISSIONS.VIEW_CAROUSEL,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.EDIT_COURSE,
    PERMISSIONS.DELETE_COURSE,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.CREATE_UNIVERSITY,
    PERMISSIONS.EDIT_UNIVERSITY,
    PERMISSIONS.DELETE_UNIVERSITY,
    PERMISSIONS.VIEW_UNIVERSITY,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.EDIT_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.MANAGE_DOCUMENTS,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_CONTACT,
    PERMISSIONS.MANAGE_CONTACT,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.ACCESS_ADMIN_PORTAL
  ],

  [ROLES.EDITOR]: [
    // View all sections, approve/reject articles only
    PERMISSIONS.VIEW_ARTICLE,
    PERMISSIONS.APPROVE_ARTICLE,
    PERMISSIONS.REJECT_ARTICLE,
    PERMISSIONS.VIEW_CATEGORY,
    PERMISSIONS.VIEW_HERO_CONTENT,
    PERMISSIONS.VIEW_CAROUSEL,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.VIEW_UNIVERSITY,
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.VIEW_CONTACT,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.ACCESS_ADMIN_PORTAL
  ],

  [ROLES.CONTENT_WRITER]: [
    // Create articles and edit own articles
    PERMISSIONS.CREATE_ARTICLE,
    PERMISSIONS.EDIT_OWN_ARTICLE,
    PERMISSIONS.DELETE_OWN_ARTICLE,
    PERMISSIONS.VIEW_ARTICLE,
    PERMISSIONS.VIEW_CATEGORY,
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.ACCESS_ADMIN_PORTAL
  ],

  [ROLES.VIEWER]: [
    // Read-only access, no admin portal
    PERMISSIONS.VIEW_ARTICLE,
    PERMISSIONS.VIEW_CATEGORY,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.VIEW_UNIVERSITY
  ]
};

/**
 * Get permissions for a role
 * @param {string} role - Role name
 * @returns {string[]} Array of permissions
 */
const getPermissionsForRole = (role) => {
  return ROLE_PERMISSIONS[role] || [];
};

/**
 * Get permissions as comma-separated string
 * @param {string} role - Role name
 * @returns {string} Comma-separated permissions
 */
const getPermissionsString = (role) => {
  const permissions = getPermissionsForRole(role);
  return permissions.join(',');
};

/**
 * Check if a role has a specific permission
 * @param {string} role - Role name
 * @param {string} permission - Permission to check
 * @returns {boolean} True if role has permission
 */
const hasPermission = (role, permission) => {
  const permissions = getPermissionsForRole(role);
  return permissions.includes(permission);
};

/**
 * Check if permissions string includes a specific permission
 * @param {string|array} permissionsString - Comma-separated permissions or array
 * @param {string} permission - Permission to check
 * @returns {boolean} True if has permission
 */
const checkPermission = (permissionsString, permission) => {
  if (!permissionsString) return false;

  // Handle array input
  if (Array.isArray(permissionsString)) {
    return permissionsString.includes(permission);
  }

  // Handle string input
  if (typeof permissionsString === 'string') {
    const permissions = permissionsString.split(',').map(p => p.trim());
    return permissions.includes(permission);
  }

  // Handle object input (shouldn't happen, but just in case)
  console.warn('checkPermission received unexpected type:', typeof permissionsString);
  return false;
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
  getPermissionsString,
  hasPermission,
  checkPermission
};
