/**
 * Update Role Permissions Script
 * Ensures all roles have correct permissions for admin portal access
 */

require('dotenv').config();
const { sequelize } = require('../config/database');
const { RoleType } = require('../models');

const rolePermissions = {
  'ADMIN': 'ALL,CREATE_USER,VIEW_USER,EDIT_USER,DELETE_USER,CREATE_ADMIN,DELETE_ADMIN,MANAGE_ADMINS,CREATE_ARTICLE,VIEW_ARTICLE,EDIT_OWN_ARTICLE,EDIT_ANY_ARTICLE,DELETE_ARTICLE,PUBLISH_ARTICLE,APPROVE_ARTICLE,REJECT_ARTICLE,CREATE_CATEGORY,EDIT_CATEGORY,DELETE_CATEGORY,VIEW_CATEGORY,MANAGE_HERO_CONTENT,MANAGE_DOCUMENTS,MANAGE_ROLES,MANAGE_PERMISSIONS,VIEW_ANALYTICS,SYSTEM_SETTINGS,CREATE_BLOG,EDIT_ANY_BLOG,DELETE_ANY_BLOG,VIEW_BLOG,PUBLISH_BLOG,CREATE_CAROUSEL,EDIT_CAROUSEL,DELETE_CAROUSEL,VIEW_CAROUSEL,CREATE_COURSE,EDIT_COURSE,DELETE_COURSE,VIEW_COURSE,CREATE_UNIVERSITY,EDIT_UNIVERSITY,DELETE_UNIVERSITY,VIEW_UNIVERSITY,VIEW_CONTACT,MANAGE_CONTACT,VIEW_REPORTS,VIEW_SETTINGS,EDIT_SETTINGS,ACCESS_ADMIN_PORTAL,CREATE_HERO_CONTENT,EDIT_HERO_CONTENT,DELETE_HERO_CONTENT,VIEW_HERO_CONTENT,CREATE_DOCUMENT,EDIT_DOCUMENT,DELETE_DOCUMENT,VIEW_DOCUMENT',
  
  'SUPER_ADMIN': 'ALL,CREATE_USER,VIEW_USER,EDIT_USER,DELETE_USER,CREATE_ADMIN,DELETE_ADMIN,MANAGE_ADMINS,CREATE_ARTICLE,VIEW_ARTICLE,EDIT_OWN_ARTICLE,EDIT_ANY_ARTICLE,DELETE_ARTICLE,PUBLISH_ARTICLE,APPROVE_ARTICLE,REJECT_ARTICLE,CREATE_CATEGORY,EDIT_CATEGORY,DELETE_CATEGORY,VIEW_CATEGORY,MANAGE_HERO_CONTENT,MANAGE_DOCUMENTS,MANAGE_ROLES,MANAGE_PERMISSIONS,VIEW_ANALYTICS,SYSTEM_SETTINGS,CREATE_BLOG,EDIT_ANY_BLOG,DELETE_ANY_BLOG,VIEW_BLOG,PUBLISH_BLOG,CREATE_CAROUSEL,EDIT_CAROUSEL,DELETE_CAROUSEL,VIEW_CAROUSEL,CREATE_COURSE,EDIT_COURSE,DELETE_COURSE,VIEW_COURSE,CREATE_UNIVERSITY,EDIT_UNIVERSITY,DELETE_UNIVERSITY,VIEW_UNIVERSITY,VIEW_CONTACT,MANAGE_CONTACT,VIEW_REPORTS,VIEW_SETTINGS,EDIT_SETTINGS,ACCESS_ADMIN_PORTAL,CREATE_HERO_CONTENT,EDIT_HERO_CONTENT,DELETE_HERO_CONTENT,VIEW_HERO_CONTENT,CREATE_DOCUMENT,EDIT_DOCUMENT,DELETE_DOCUMENT,VIEW_DOCUMENT',
  
  'CONTENT_MANAGER': 'CREATE_ARTICLE,VIEW_ARTICLE,EDIT_OWN_ARTICLE,EDIT_ANY_ARTICLE,DELETE_ARTICLE,PUBLISH_ARTICLE,APPROVE_ARTICLE,REJECT_ARTICLE,CREATE_BLOG,EDIT_ANY_BLOG,DELETE_ANY_BLOG,VIEW_BLOG,PUBLISH_BLOG,CREATE_CATEGORY,EDIT_CATEGORY,DELETE_CATEGORY,VIEW_CATEGORY,CREATE_HERO_CONTENT,EDIT_HERO_CONTENT,DELETE_HERO_CONTENT,VIEW_HERO_CONTENT,MANAGE_HERO_CONTENT,CREATE_CAROUSEL,EDIT_CAROUSEL,DELETE_CAROUSEL,VIEW_CAROUSEL,CREATE_COURSE,EDIT_COURSE,DELETE_COURSE,VIEW_COURSE,CREATE_UNIVERSITY,EDIT_UNIVERSITY,DELETE_UNIVERSITY,VIEW_UNIVERSITY,CREATE_DOCUMENT,EDIT_DOCUMENT,DELETE_DOCUMENT,VIEW_DOCUMENT,MANAGE_DOCUMENTS,VIEW_USER,VIEW_CONTACT,MANAGE_CONTACT,VIEW_ANALYTICS,VIEW_REPORTS,VIEW_SETTINGS,EDIT_SETTINGS,ACCESS_ADMIN_PORTAL',
  
  'EDITOR': 'VIEW_ARTICLE,APPROVE_ARTICLE,REJECT_ARTICLE,VIEW_BLOG,VIEW_CATEGORY,VIEW_HERO_CONTENT,VIEW_CAROUSEL,VIEW_COURSE,VIEW_UNIVERSITY,VIEW_DOCUMENT,VIEW_CONTACT,VIEW_ANALYTICS,VIEW_REPORTS,VIEW_SETTINGS,ACCESS_ADMIN_PORTAL',
  
  'CONTENT_WRITER': 'CREATE_ARTICLE,EDIT_OWN_ARTICLE,DELETE_OWN_ARTICLE,VIEW_ARTICLE,CREATE_BLOG,EDIT_OWN_BLOG,DELETE_OWN_BLOG,VIEW_BLOG,VIEW_CATEGORY,VIEW_DOCUMENT,ACCESS_ADMIN_PORTAL',
  
  'VIEWER': 'VIEW_ARTICLE,VIEW_BLOG,VIEW_CATEGORY,VIEW_COURSE,VIEW_UNIVERSITY'
};

(async () => {
  try {
    await sequelize.authenticate();
    console.log('Database connected\n');
    console.log('Updating role permissions...\n');

    for (const [roleCode, permissions] of Object.entries(rolePermissions)) {
      const roles = await RoleType.findAll({ where: { code: roleCode } });
      
      for (const role of roles) {
        await role.update({ 
          default_permission: permissions,
          is_enable: true 
        });
        console.log(`✅ Updated ${role.name} (ID: ${role.id}, Code: ${roleCode})`);
      }
    }

    console.log('\n✅ All role permissions updated successfully!');
    console.log('\nRoles with ACCESS_ADMIN_PORTAL:');
    console.log('  - ADMIN');
    console.log('  - SUPER_ADMIN');
    console.log('  - CONTENT_MANAGER');
    console.log('  - EDITOR');
    console.log('  - CONTENT_WRITER');
    console.log('\nRoles WITHOUT ACCESS_ADMIN_PORTAL:');
    console.log('  - VIEWER (read-only, no admin access)');
    
    process.exit(0);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
})();
